import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { ToastProvider } from "@/components/ToastProvider";
import { Sidebar } from "@/components/Sidebar";
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col bg-slate-50">
                <ToastProvider>

                    <div className="flex flex-col-reverse md:flex-row h-screen bg-white md:items-center overflow-hidden">
                        <Sidebar />
                        <main className="flex-1 w-full overflow-y-auto">{children}</main>
                    </div>

                </ToastProvider>
            </body>
        </html>
    );
}
